# Generated by Django 3.2.18 on 2023-05-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astronaut',
            fields=[
                ('astronautId', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID астронавта')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО астронавта')),
                ('age', models.IntegerField(verbose_name='Возраст астронавта')),
                ('number_of_flights', models.IntegerField(verbose_name='Количество полётов астронавта')),
            ],
            options={
                'verbose_name': 'Астронавт',
                'verbose_name_plural': 'Астронавты',
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('planetId', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID планеты')),
                ('name', models.CharField(max_length=255, verbose_name='Название планеты')),
                ('number_of_satellites', models.IntegerField(verbose_name='Количество спутников')),
            ],
            options={
                'verbose_name': 'Планета',
                'verbose_name_plural': 'Планеты',
            },
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('expeditionId', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID экспедиции')),
                ('report', models.CharField(max_length=255, verbose_name='Описание экспедиции')),
                ('expedition_time', models.CharField(max_length=255, verbose_name='Время экспедиции')),
                ('astronautId', models.ForeignKey(on_delete=models.SET(-1), to='Space.astronaut', verbose_name='ID астронавта')),
                ('planetId', models.ForeignKey(on_delete=models.SET(-1), to='Space.planet', verbose_name='ID планеты')),
            ],
            options={
                'verbose_name': 'Экспедиция',
                'verbose_name_plural': 'Экспедиции',
            },
        ),
    ]
